version: "3.9"
services:
    web-php:
        build:
            context: .
            dockerfile: ./demo/Dockerfile
        container_name: php-fpm
        volumes:
            - www:/demo/public:ro

    web-nginx:
        image: nginx:latest
        depends_on:
            - web-php
        container_name: web-nginx
        volumes:
            - www:/usr/share/nginx/html:ro
            - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"
        ports:
            - "127.0.0.1:80:80"
volumes:
    www: